apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: nats
data:
  nats.conf: |
    # Configuração Básica
    port: 4222
    http_port: 8222
    server_name: nats-0
    
    # JetStream (Persistência)
    jetstream {
        store_dir: "/data"
        max_mem: 1G
        max_file: 5G
    }

    # Autenticação
    authorization {
        users = [
            { user: "admin", password: "Admin@123" }
        ]
    }

    # Logging
    debug: false
    trace: false
    logtime: true
