apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nats-monitor-ingress
  namespace: nats
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: local-ca
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - nats-monitor.home.arpa
    secretName: nats-monitor-tls
  rules:
  - host: nats-monitor.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nats
            port:
              number: 8222
