---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: rabbitmq-amqp
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: amqp
spec:
  entryPoints:
    - amqp
  routes:
  - match: HostSNI(`*`)
    services:
    - name: rabbitmq
      port: 5672
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: rabbitmq-amqps
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: amqps
spec:
  entryPoints:
    - amqps
  routes:
  - match: HostSNI(`*`)
    services:
    - name: rabbitmq
      port: 5671
  tls:
    passthrough: true
