apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: loki-redirect
  namespace: monitoring
spec:
  redirectRegex:
    regex: ".*"
    replacement: "https://grafana.home.arpa/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%22refId%22:%22A%22%7D%5D"
    permanent: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: local-ca
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: monitoring-loki-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - loki.home.arpa
    secretName: loki-tls
  rules:
  - host: loki.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loki
            port:
              number: 3100
