apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
data:
  rabbitmq.conf: |
    ## Minimal config
    ## Keep defaults; only disable guest loopback for external access
    loopback_users.guest = false
    
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_prometheus].