apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-tcp-services
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
data:
  5672: "rabbitmq/rabbitmq:5672"
  5671: "rabbitmq/rabbitmq:5671"