apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/seu-usuario/k8s-cluster-config
      revision: HEAD
      directories:
      - path: infrastructure/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/seu-usuario/k8s-cluster-config
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/seu-usuario/k8s-cluster-config
      revision: HEAD
      directories:
      - path: infrastructure/monitoring
  template:
    metadata:
      name: 'monitoring-{{path.basename}}'
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: monitoring
      source:
        repoURL: https://github.com/seu-usuario/k8s-cluster-config
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: data-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/seu-usuario/k8s-cluster-config
      revision: HEAD
      directories:
      - path: applications/redis-ha
  template:
    metadata:
      name: 'data-{{path.basename}}'
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: data
      source:
        repoURL: https://github.com/seu-usuario/k8s-cluster-config
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: redis-ha
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
          
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backup-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/seu-usuario/k8s-cluster-config
      revision: HEAD
      files:
      - path: "infrastructure/backup/velero-config.yaml"
  template:
    metadata:
      name: 'velero-backup'
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: backup
      source:
        repoURL: https://github.com/seu-usuario/k8s-cluster-config
        targetRevision: HEAD
        path: 'infrastructure/backup'
      destination:
        server: https://kubernetes.default.svc
        namespace: velero
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      revisionHistoryLimit: 10