apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elk
  labels:
    app.kubernetes.io/name: elk
    app.kubernetes.io/component: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: homelab-elasticsearch
    node.name: ${NODE_NAME}
    node.roles: [ master, data, ingest ]
    discovery.type: single-node
    network.host: 0.0.0.0
    xpack.security.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false
    indices.query.bool.max_clause_count: 2048
  jvm.options: |
    -Xms512m
    -Xmx512m
    -XX:+UseG1GC
