apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-ingress
  namespace: elk
  labels:
    app.kubernetes.io/name: elk
    app.kubernetes.io/component: elasticsearch
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: local-ca
spec:
  ingressClassName: traefik
  rules:
    - host: elasticsearch.home.arpa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elasticsearch
                port:
                  name: http
  tls:
    - hosts:
        - elasticsearch.home.arpa
      secretName: elasticsearch-tls