apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: elk
  labels:
    app.kubernetes.io/name: elk
    app.kubernetes.io/component: logstash
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      if [kubernetes] {
        mutate { add_field => { "[fields][source]" => "kubernetes" } }
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        user => "${ELASTICSEARCH_USERNAME}"
        password => "${ELASTICSEARCH_PASSWORD}"
        index => "logs-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }