apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: kong
data:
  kong.conf: |
    database = off
    proxy_listen = 0.0.0.0:8000, 0.0.0.0:8443 ssl
    admin_listen = 0.0.0.0:8001, 0.0.0.0:8444 ssl
    status_listen = 0.0.0.0:8100
    declarative_config = /kong_configs/kong.yml
  kong.yml: |
    _format_version: "1.1"
    services:
    - name: example-service
      url: http://httpbin.org
      routes:
      - name: example-route
        paths:
        - /example
