apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console-ingress
  namespace: minio
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: local-ca
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - minio-console.home.arpa
    secretName: minio-console-tls
  rules:
  - host: minio-console.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-console
            port:
              number: 9001
