apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-s3-ingress
  namespace: minio
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: local-ca
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts: ["minio-s3.home.arpa"]
    secretName: minio-s3-tls
  rules:
  - host: minio-s3.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9000
