apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-s3-ingress
  namespace: minio
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: local-ca
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - minio-s3.home.arpa
    secretName: minio-s3-tls
  rules:
  - host: minio-s3.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-service
            port:
              number: 9000
