apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-stats-ingress
  namespace: redis
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: local-ca
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: public
  tls:
  - hosts:
    - redis-stats.home.arpa
    secretName: redis-stats-tls
  rules:
  - host: redis-stats.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redis-proxy-service
            port:
              number: 8404