apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-tcp-microk8s-conf
  namespace: ingress
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: tcp-services
data:
  "5672": "rabbitmq/rabbitmq:5672"
  "5671": "rabbitmq/rabbitmq:5671"
  "6380": "redis/redis-proxy-service:6380"
  "6382": "redis/redis-proxy-service:6382"